# setup service
version: '3'

services:
  djangoserver:
    container_name: dj-backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app 

  djredis:
    image: redis:latest
    container_name: dj-redis

  celery:
    container_name: dj-celery
    build: .
    command: celery -A project worker -l INFO
    restart: always
    depends_on:
      - djredis





